"""
prompts/__init__.py
"""
from .system_prompts import (
    CODE_GENERATION_PROMPT,
    CODE_EXPLANATION_PROMPT,
    BUG_DETECTION_PROMPT,
    CODE_CONVERSION_PROMPT,
    DOCSTRING_GENERATION_PROMPT,
    UNIT_TEST_PROMPT,
    CODE_REFACTORING_PROMPT,
    PAIR_PROGRAMMER_PROMPT,
    REPOSITORY_ANALYSIS_PROMPT,
)

__all__ = [
    "CODE_GENERATION_PROMPT",
    "CODE_EXPLANATION_PROMPT",
    "BUG_DETECTION_PROMPT",
    "CODE_CONVERSION_PROMPT",
    "DOCSTRING_GENERATION_PROMPT",
    "UNIT_TEST_PROMPT",
    "CODE_REFACTORING_PROMPT",
    "PAIR_PROGRAMMER_PROMPT",
    "REPOSITORY_ANALYSIS_PROMPT",
]
